# ======================================================================
# GitHub Actions Workflow
#
# Este pipeline ejecuta automáticamente las pruebas Cypress
# cada vez que hacemos un Push o Pull Request.
#
# Además:
#
# ✔ Instala Node
# ✔ Instala dependencias
# ✔ Ejecuta Cypress
# ✔ Genera reporte Allure
# ✔ Publica el reporte como Artifact
# ======================================================================

name: Cypress Tests

# --------------------------------------------------------------
# ¿Cuándo se ejecutará?
#
# Cada Push
#
# Cada Pull Request
#
# hacia la rama main.
# --------------------------------------------------------------

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            # ----------------------------------------------------------
            # Descarga el código del repositorio.
            # ----------------------------------------------------------

            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------------------
            # Instala Node.js
            #
            # Nuestro proyecto usa Node porque Cypress
            # funciona sobre Node.
            # ----------------------------------------------------------

            - name: Setup Node.js

              uses: actions/setup-node@v4

              with:
                  node-version: 20

            # ----------------------------------------------------------
            # Instala package.json
            #
            # npm ci
            #
            # Es preferible a npm install
            # porque instala exactamente las versiones
            # del package-lock.json
            # ----------------------------------------------------------

            - name: Install dependencies

              run: npm ci

            # ----------------------------------------------------------
            # Ejecuta TODAS las pruebas.
            # ----------------------------------------------------------

            - name: Run Cypress Tests

              run: npm run cy:run

            # ----------------------------------------------------------
            # Verificamos que exista la carpeta allure-results.
            #
            # Esto sirve para depurar.
            # ----------------------------------------------------------

            - name: Verify Allure Results

              if: always()

              run: |

                  echo "Contenido del proyecto"

                  ls -la

                  echo ""

                  echo "Contenido allure-results"

                  ls -la allure-results || true

            # ----------------------------------------------------------
            # Genera el reporte HTML de Allure.
            # ----------------------------------------------------------

            - name: Generate Allure Report

              if: always()

              run: npm run allure:generate

            # ----------------------------------------------------------
            # Verificamos que el reporte exista.
            # ----------------------------------------------------------

            - name: Verify Allure Report

              if: always()

              run: |

                  echo "Contenido allure-report"

                  ls -la allure-report || true

            # ----------------------------------------------------------
            # Publicamos el reporte para descargarlo
            # desde GitHub.
            # ----------------------------------------------------------

            - name: Upload Allure Report

              if: always()

              uses: actions/upload-artifact@v4

              with:
                  name: allure-report

                  path: allure-report
